name: data-security

services:
  postgres:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: security
